apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: build
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    helm:
      values: |
        master:
          useSecurity: true
          adminUser: admin
          adminPassword: admin
          numExecutors: 1
          installPlugins:
            - kubernetes:1.21.1
            - workflow-job:2.36
            - workflow-aggregator:2.6
            - credentials-binding:1.20
            - git:3.12.1
            - command-launcher:1.3
            - github-branch-source:2.5.8
            - docker-workflow:1.21
            - pipeline-utility-steps:2.3.1
          overwritePlugins: true
          ingress:
            enabled: true
            hostName: jenkins.codechallenge.reisys.io
            #path: /jenkins
            annotations:
              kubernetes.io/ingress.class: nginx
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 2.0.1
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')