apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
spec:
  destination:
    namespace: build
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sonatype-nexus
    helm:
      values: |
        nexusProxy:
            env:
                nexusDockerHost: container.codechallenge.reisys.io
                nexusHttpHost: nexus.codechallenge.reisys.io
        nexusBackup:
            env:
                targetBucket: "gs://my-nexus-backup"
            persistence:
                storageClass: gp2
        ingress:
            enabled: true
            annotations:
                kubernetes.io/ingress.class: nginx
        persistence:
            storageClass: gp2
            storageSize: 1024Gi
        resources:
            requests:
                cpu: 250m
                memory: 4800Mi
    repoURL: https://oteemo.github.io/charts
    targetRevision: 2.1.0